# frozen_string_literal: true

require_relative "depot/version"
require_relative "depot/paths"
require_relative "depot/result"
require_relative "depot/settings"
require_relative "depot/manifest_store"
require_relative "depot/assets"
require_relative "depot/packages/archive"
require_relative "depot/packages/deb"
require_relative "depot/packages/rpm"
require_relative "depot/packages/flatpak_ref"
require_relative "depot/inspector"
require_relative "depot/installer"
require_relative "depot/uninstaller"
require_relative "depot/app_customizer"
require_relative "depot/doctor"
require_relative "depot/launcher"
require_relative "depot/source_resolver"
require_relative "depot/sandbox"
require_relative "depot/update_downloader"
require_relative "depot/updater"
